### ISSUE TITLE
Is there a max size for a graymatter line?

### ISSUE THREAD

**Issue by JeremieLitzler** [jonschlinkert/gray-matter#115]
Hi,

I have found that the following works:

```yaml
---
title: 'The Responsive Web Design Bootcamp - Course review'
subtitle: 'Learn to build mobile-friendly websites in a complete course using an interactive classroom.'
author: 'Jeremie Litzler'
date: '16 Mar 2020'
hero_image: ../static/images/webresponsive-bootcamp-by-scrimba.png
category: 'Web development, Reviews'
---
```

But this one doesn't: 

```yaml
---
title: 'The Responsive Web Design Bootcamp - Course review'
subtitle: 'Let's build the future with a mobile-friendly websites in a complete course using an interactive classroom.'
author: 'Jeremie Litzler'
date: '16 Mar 2020'
hero_image: ../static/images/webresponsive-bootcamp-by-scrimba.png
category: 'Web development, Reviews'
---
```

and it gives out this error: `YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4`.

The length of `subtitle` is the cause.

**Is there a maximum line size per line?**
Or am I using it improperly?

The source is [here](https://github.com/JeremieLitzler/iamjeremie.me/tree/master/posts).

**Comment by robertmassaioli** [comment]
The problem is that, in the subtitle example, you are using the `'` symbol three times on the one line:

``` yaml
---
subtitle: 'Let's'
---
```

Does this example highlight the problem? The Yaml parser thinks that there are extra characters after the `'Let'` that it does not know how to handle.

The correct way to write your example is:

``` yaml
---
title: The Responsive Web Design Bootcamp - Course review
subtitle: Let's build the future with a mobile\-friendly websites in a complete course
  using an interactive classroom.'
author: Jeremie Litzler
date: 16 Mar 2020
hero_image: "../static/images/webresponsive-bootcamp-by-scrimba.png"
category: Web development, Reviews
```

Hope that helps. To validate this yourself, I sometimes find that it helps to convert your YAML to JSON, write it correctly in JSON, and then convert it back to YAML. This tool helps: https://www.json2yaml.com/
