### ISSUE TITLE
Do it support multiple documents in one file?

### ISSUE THREAD

**Issue by fghhfg** [jonschlinkert/gray-matter#21]
like [this](http://www.yaml.org/spec/1.2/spec.html#id2761803):
```yaml
---
Time: 2001-11-23 15:01:42 -5
User: ed
Warning:
  This is an error message
  for the log file
---
Time: 2001-11-23 15:02:31 -5
User: ed
Warning:
  A slightly different error
  message.
---
Date: 2001-11-23 15:03:17 -5
User: ed
Fatal:
  Unknown variable "bar"
Stack:
  - file: TopClass.py
    line: 23
    code: |
      x = MoreObject("345\n")
  - file: MoreClass.py
    line: 58
    code: |-
      foo = bar
```

I tried, but failed...
```js
> var matter = require('gray-matter');
> matter('---\ntitle: Front Matter\n---\nThis is content.\n---\ndddsss');
{ orig: '---\ntitle: Front Matter\n---\nThis is content.\n---\ndddsss',
  data: { title: 'Front Matter' },
  content: 'This is content.\n---\ndddsss' }
```

I want to save multiple part html, 
```yaml
title: aaa
description: bbb
---
<div>
    <div id="ad-535" class="ad-535"></div>
    <div id="ad-267" class="ad-267 ad-middle"></div>
    <div id="ad-458" class="ad-458"></div>
</div>
---
<div>
    <div id="ad-535" class="ad-535"></div>
    <div id="ad-267" class="ad-267 ad-middle"></div>
    <div id="ad-458" class="ad-458"></div>
</div>
```

and I don't want to write something like this:
```yaml
part1: <div><div id="ad-535" class="ad-535"></div><div id="ad-267" class="ad-267 ad-middle"></div><div id="ad-458" class="ad-458"></div></div>
part2: <div><div id="ad-535" class="ad-535"></div><div id="ad-267" class="ad-267 ad-middle"></div><div id="ad-458" class="ad-458"></div></div>
```
