### ISSUE TITLE
Parser for org mode tags [FEATURE REQUEST]

### ISSUE THREAD

**Issue by HaoZeke** [jonschlinkert/gray-matter#79]
Similar to YAML, org files often have a particular markup:

```org-mode
#+TITLE:       Something
#+AUTHOR:      Someone
#+EMAIL:       e@mali.com
#+DATE:        2015-06-12 Sun
#+URI:         /blog/%y/%m/%d/title/
#+KEYWORDS:    some,stuff,this,says
#+TAGS:     blah
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: I speak of tests
```

Which should be equivalent to:

``` yaml
title:       Something
author:      Someone
email:       e@mali.com
date:        2015-06-12 Sun
uri:         /blog/%y/%m/%d/title/
keywods:    some,stuff,this,says
tags:     blah
language:    en
options:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
description: I speak of tests
```

Would this be a viable feature?
